######################################################################
# Automatically generated by qmake (2.01a) lun feb 25 00:20:49 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
