######################################################################
# Automatically generated by qmake (2.01a) vie jul 11 18:58:37 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
