######################################################################
# Automatically generated by qmake (2.01a) dom dic 21 12:58:45 2008
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
