######################################################################
# Automatically generated by qmake (2.01a) mié abr 16 11:19:07 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += piechart.h
SOURCES += main.cpp piechart.cpp
