######################################################################
# Automatically generated by qmake (2.01a) mar feb 19 16:15:26 2008
######################################################################

CONFIG += qt
QT += svg

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
