######################################################################
# Automatically generated by qmake (2.01a) vie ago 29 14:12:53 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += main.moc
SOURCES += main.cpp
