######################################################################
# Automatically generated by qmake (2.01a) vie may 2 16:24:48 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
