######################################################################
# Automatically generated by qmake (2.01a) jue jul 24 00:54:15 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += window.h
SOURCES += main.cpp window.cpp
