######################################################################
# Automatically generated by qmake (2.01a) jue jul 3 01:40:52 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
