######################################################################
# Automatically generated by qmake (2.01a) lun dic 22 11:36:58 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
