######################################################################
# Automatically generated by qmake (2.01a) mié mar 12 16:38:31 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
