######################################################################
# Automatically generated by qmake (2.01a) dom ago 31 14:54:03 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mass.h surface.h vector2d.h
SOURCES += main.cpp
