######################################################################
# Automatically generated by qmake (2.01a) mar feb 19 22:18:21 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
