######################################################################
# Automatically generated by qmake (2.01a) sáb dic 27 20:04:26 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
