######################################################################
# Automatically generated by qmake (2.01a) dom abr 20 12:34:34 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
