######################################################################
# Automatically generated by qmake (2.01a) lun feb 25 00:21:25 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += main.moc
SOURCES += main2.cpp
